name: Compare

on:
  workflow_dispatch:
    inputs:
      base:
        description: "Base webpack version (git)"
        default: "v5.21.2"
        required: true
      current:
        description: "current webpack version (git)"
        default: "master"
        required: true

jobs:
  bench:
    strategy:
      fail-fast: false
      matrix:
        base:
          - "${{ github.event.inputs.base }}"
        current:
          - "${{ github.event.inputs.current }}"
        case:
          - minimal
          - esbuild-three
        scenario:
          - development-default-build
          - development-cached-build
          - development-cached-pnp-build
          - development-cached-rebuild
          # - production-default-build
          # - production-cached-build
          # - production-source-map-build
          # - production-source-map-cached-build
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.inputs.base }} vs ${{ github.event.inputs.current }}
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: yarn-${{ matrix.case }}-${{ github.event.inputs.base }}
          restore-keys: |
            yarn-${{ matrix.case }}-
            yarn-
      - run: node bin/compare.js ${{ matrix.case }} ${{ matrix.scenario }} ${{ github.event.inputs.base }} ${{ github.event.inputs.current }}
      - uses: actions/upload-artifact@v2
        with:
          name: compare-results
          path: output
  report:
    needs: [bench]
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.inputs.base }} vs ${{ github.event.inputs.current }}
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - uses: actions/download-artifact@v2
        with:
          name: compare-results
          path: output
      - run: node bin/report.js
