name: Measure date

on:
  workflow_dispatch:
    inputs:
      date:
        description: "Date to measure (yyyy-mm-dd)"
        default: "2021-01-01"
        required: true
jobs:
  bench:
    strategy:
      fail-fast: false
      matrix:
        case:
          - common-libs
          - esbuild-three
        scenario:
          - development-build
          - development-build+persistent-cache
          - development-build+pnp
          - development-rebuild
          - production-build
          - production-build+source-map
          - production-build+no-minimize
          - production-build+no-minimize+no-concatenation
          - production-build+persistent-cache
          - production-build+source-map+persistent-cache
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.inputs.date }}
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: yarn-${{ matrix.case }}-${{ github.event.inputs.date }}
          restore-keys: |
            yarn-${{ matrix.case }}-
            yarn-
      - run: yarn
      - run: node bin/measure-mean.js ${{ matrix.case }} ${{ matrix.scenario }} ${{ github.event.inputs.date }}
      - uses: actions/upload-artifact@v2
        with:
          name: measure-results
          path: output
  upload:
    needs: [bench]
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.inputs.date }}
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: yarn-upload-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            yarn-upload-
            yarn-
      - run: yarn
      - uses: actions/download-artifact@v2
        with:
          name: measure-results
          path: output
      - run: node bin/upload.js ${{ github.event.inputs.date }}
